name: "godot-ci export"
on: 
    push:
        branches: [master]

env:
    godot_version: 4.3
    export_name: Survivor
    project_path: Survivor

jobs:
    build:
        name: Export
        runs-on: ubuntu-20.04
        container:
            image: barichello/godot-ci:4.3
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                lfs: true
            - name: Setup
              run: |
                mkdir -v -p ~/.local/share/godot/export_templates/
                mkdir -v -p ~/.config/
                mv /root/.config/godot ~/.config/godot
                mv /root/.local/share/godot/export_templates/${godot_version}.stable ~/.local/share/godot/export_templates/${godot_version}.stable
            - name: Build
              run: |
                mkdir -v -p build
                export_dir="$(readlink -f build)"
                cd $project_path
                godot --headless --verbose --export-pack "Windows Desktop" "$export_dir/windows/$export_name.exe" 
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: windows
                path: build
                