name: "godot-ci export"
on: push

# NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` below to ".".

env:
  godot_version: 4.3
  export_name: survivor
  project_path: survivor

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${godot_version}.stable ~/.local/share/godot/export_templates/${godot_version}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          export_dir="$(readlink -f build)"
          cd $project_path
          godot --headless --verbose --export-release "Windows Desktop" "$export_dir/windows/$export_dir.exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/windows
